# Generated by Django 3.0.2 on 2021-10-01 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waferId', models.CharField(max_length=100)),
                ('waferNo', models.TextField()),
                ('lotId', models.CharField(max_length=100)),
                ('lotNo', models.TextField()),
                ('testId', models.CharField(max_length=100)),
                ('testNo', models.TextField()),
                ('defectId', models.CharField(max_length=100)),
                ('defectNo', models.TextField()),
            ],
        ),
    ]
